# Generated by Django 5.2 on 2025-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('year', models.DateField(verbose_name='Год выхода')),
                ('cover', models.ImageField(upload_to='albums/', verbose_name='Обложка альбома')),
                ('release_type', models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл')], default='album', max_length=10, verbose_name='Тип релиза')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-year'],
            },
        ),
    ]
