# Generated by Django 5.2 on 2025-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_concert_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='meeting',
            field=models.URLField(blank=True, null=True, verbose_name='Cсылка на встречу'),
        ),
    ]
