# Generated by Django 5.2 on 2025-05-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_concert_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='meeting',
            field=models.URLField(verbose_name='Cсылка на встречу'),
        ),
    ]
