# Generated by Django 5.2 on 2025-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Навзвание концерта')),
                ('date', models.DateField(verbose_name='Дата концерта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('ticket', models.URLField(verbose_name='Ссылка на покупку билетов')),
                ('meeting', models.URLField(verbose_name='Cсылка на встречу')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['-date'],
            },
        ),
    ]
