# Generated by Django 5.2 on 2025-05-05 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_concert_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2025)], verbose_name='Год релиза')),
                ('cover', models.ImageField(upload_to='albums/', verbose_name='Обложка альбома')),
                ('release_type', models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл')], default='album', max_length=10, verbose_name='Тип релиза')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-year'],
            },
        ),
    ]
