# Generated by Django 5.2 on 2025-05-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_album_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='age_limit',
        ),
    ]
